const { Card } = require("../models");

const cardData = [
  {
    id: 1,
    front: "Good-Bye",
    back: "Adios",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 2,
    front: "Hello",
    back: "Hola",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 3,
    front: "Here",
    back: "Aqui",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 4,
    front: "There",
    back: "Alli",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 5,
    front: "Now",
    back: "Ahora",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 6,
    front: "School",
    back: "Escuela",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 7,
    front: "Shop",
    back: "Tienda",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 8,
    front: "Bathroom",
    back: "Baño",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 9,
    front: "City",
    back: "Ciudad",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 10,
    front: "Country",
    back: "Pais",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 11,
    front: "Thing",
    back: "Cosa",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 12,
    front: "Nothing",
    back: "Nada",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 13,
    front: "House",
    back: "Casa",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 14,
    front: "Car",
    back: "Coche",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 15,
    front: "Language",
    back: "Idioma",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 16,
    front: "Water",
    back: "Agua",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 17,
    front: "Movie",
    back: "Pelicula",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 18,
    front: "Man",
    back: "Hombre",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 19,
    front: "Woman",
    back: "Mujer",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 20,
    front: "Chico",
    back: "Boy",
    dueDate: 12345,
    deck_id: 1,
    isLearned: false,
  },
  {
    id: 21,
    front: "To Be(permanent)",
    back: "Ser",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 22,
    front: "To Be(non-permanent)",
    back: "Estar",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 23,
    front: "To exist",
    back: "Haber",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 24,
    front: "To have",
    back: "Tener",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 25,
    front: "To do or make",
    back: "Hacer",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 26,
    front: "Can Do",
    back: "Poder",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 27,
    front: "To See",
    back: "Ver",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 28,
    front: "To Go",
    back: "Ir",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 29,
    front: "To Give",
    back: "Dar",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 30,
    front: "To know",
    back: "Saber",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 31,
    front: "To Want or To Love",
    back: "Querer",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 32,
    front: "To believe",
    back: "Creer",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 33,
    front: "To Talk",
    back: "Hablar",
    dueDate: 12345,
    deck_id: 2,
    isLearned: false,
  },
  {
    id: 34,
    front: "To Carry",
    back: "Llevar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 35,
    front: "To Find",
    back: "Encontrar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 36,
    front: "To Like",
    back: "Gustar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 37,
    front: "To Tell",
    back: "Decir",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 38,
    front: "To Come",
    back: "Venir",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 39,
    front: "To Think",
    back: "Pensar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 40,
    front: "To Understand",
    back: "Entender",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 41,
    front: "To Read",
    back: "Leer",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 42,
    front: "To Eat",
    back: "Comer",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 43,
    front: "To Drink",
    back: "Beber",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 44,
    front: "To Work",
    back: "Trabajar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 45,
    front: "To Use",
    back: "Usar",
    dueDate: 12345,
    deck_id: 3,
    isLearned: false,
  },
  {
    id: 46,
    front: "All",
    back: "Todo",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },
  {
    id: 47,
    front: "Some",
    back: "Alguno",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 48,
    front: "More",
    back: "Mas",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 49,
    front: "Less",
    back: "Menos",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 50,
    front: "Very",
    back: "Muy",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 51,
    front: "A Lot",
    back: "Mucho",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 52,
    front: "Other",
    back: "Otro",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 53,
    front: "Almost",
    back: "Casi",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 54,
    front: "Same",
    back: "Mismo",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 55,
    front: "Like This",
    back: "Asi",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 56,
    front: "Also",
    back: "Tambien",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 57,
    front: "Until, Even",
    back: "Hasta",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 58,
    front: "Large",
    back: "Grande",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 59,
    front: "Small",
    back: "Pequeno",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 60,
    front: "Well",
    back: "Bien",
    dueDate: 12345,
    deck_id: 4,
    isLearned: false,
  },  {
    id: 61,
    front: "A Little",
    back: "Poco",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 62,
    front: "Always",
    back: "Siempre",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 63,
    front: "Never",
    back: "Nunca",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 64,
    front: "Each",
    back: "Cada",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 65,
    front: "New",
    back: "Nuevo",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 66,
    front: "Old",
    back: "Antigua",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 67,
    front: "Good",
    back: "Bueno",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 68,
    front: "Bad",
    back: "Mal",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 69,
    front: "High",
    back: "Alto",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 70,
    front: "Low",
    back: "Bajo",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 71,
    front: "Far",
    back: "Lejos",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 72,
    front: "Near",
    back: "Cerca",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 73,
    front: "Beautiful",
    back: "Hermosa",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 74,
    front: "Ugly",
    back: "Feo",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 75,
    front: "Dificult",
    back: "Dificil",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 76,
    front: "Easy",
    back: "Facil",
    dueDate: 12345,
    deck_id: 5,
    isLearned: false,
  },
  {
    id: 78,
    front: "Camera",
    back: "Cámara",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  },
  {
    id: 79,
    front: "Electric",
    back: "Eléctrico",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  },
  {
    id: 80,
    front: "Country",
    back: "País",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  },
  {
    id: 81,
    front: "Heart",
    back: "Corazón",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  },
  {
    id: 82,
    front: "Number",
    back: "Número",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  },
  {
    id: 83,
    front: "Penguin",
    back: "Pingüino",
    dueDate: 12345,
    deck_id: 6,
    isLearned: false,
  }
];

const seedCards = () => Card.bulkCreate(cardData);

module.exports = seedCards;
